apiVersion: apps/v1
kind: Deployment
metadata:
  name: wanderer-search
  labels:
    app: wanderer-search
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wanderer-search
  template:
    metadata:
      labels:
        app: wanderer-search
    spec:
      affinity:
        nodeAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              preference:
                matchExpressions:
                  - key: region
                    operator: In
                    values:
                      - europe
      containers:
        - name: search
          image: getmeili/meilisearch:v1.24.0
          ports:
            - containerPort: 7700
          env:
            - name: MEILI_URL
              value: http://localhost:7700
            - name: MEILI_MASTER_KEY
              value: vODkljPcfFANYNepCHyDyGjzAMPcdHnrb6X5KyXQPWo
            - name: MEILI_NO_ANALYTICS
              value: "true"
          volumeMounts:
            - name: search-data
              mountPath: /meili_data/
          resources:
            requests:
              cpu: 100m
              memory: 256Mi
            limits:
              cpu: 1000m
              memory: 512Mi
          livenessProbe:
            httpGet:
              path: /health
              port: 7700
            initialDelaySeconds: 20
            periodSeconds: 15
            timeoutSeconds: 10
          readinessProbe:
            httpGet:
              path: /health
              port: 7700
            initialDelaySeconds: 10
            periodSeconds: 5
            timeoutSeconds: 10
      volumes:
        - name: search-data
          persistentVolumeClaim:
            claimName: wanderer-search-data
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: wanderer-db
  labels:
    app: wanderer-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wanderer-db
  template:
    metadata:
      labels:
        app: wanderer-db
    spec:
      affinity:
        nodeAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              preference:
                matchExpressions:
                  - key: region
                    operator: In
                    values:
                      - europe
      containers:
        - name: db
          image: flomp/wanderer-db
          ports:
            - containerPort: 8090
          env:
            - name: MEILI_URL
              value: http://wanderer-search:7700
            - name: MEILI_MASTER_KEY
              value: vODkljPcfFANYNepCHyDyGjzAMPcdHnrb6X5KyXQPWo
            - name: POCKETBASE_ENCRYPTION_KEY
              value: fde406459dc1f6ca6f348e1f44a9a2af
            - name: ORIGIN
              value: http://localhost:3000
          volumeMounts:
            - name: db-data
              mountPath: /pb_data
          resources:
            requests:
              cpu: 100m
              memory: 256Mi
            limits:
              cpu: 1000m
              memory: 512Mi
          livenessProbe:
            httpGet:
              path: /health
              port: 8090
            initialDelaySeconds: 20
            periodSeconds: 15
            timeoutSeconds: 10
          readinessProbe:
            httpGet:
              path: /health
              port: 8090
            initialDelaySeconds: 10
            periodSeconds: 5
            timeoutSeconds: 10
      volumes:
        - name: db-data
          persistentVolumeClaim:
            claimName: wanderer-db-data
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: wanderer
  labels:
    app: wanderer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wanderer
  template:
    metadata:
      labels:
        app: wanderer
    spec:
      affinity:
        nodeAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              preference:
                matchExpressions:
                  - key: region
                    operator: In
                    values:
                      - europe
      containers:
        - name: wanderer
          image: flomp/wanderer-web
          ports:
            - containerPort: 3000
          env:
            - name: MEILI_URL
              value: http://wanderer-search:7700
            - name: MEILI_MASTER_KEY
              value: vODkljPcfFANYNepCHyDyGjzAMPcdHnrb6X5KyXQPWo
            - name: ORIGIN
              value: http://localhost:3000
            - name: BODY_SIZE_LIMIT
              value: Infinity
            - name: PUBLIC_POCKETBASE_URL
              value: http://wanderer-db:8090
            - name: PUBLIC_DISABLE_SIGNUP
              value: "false"
            - name: UPLOAD_FOLDER
              value: /app/uploads
            - name: UPLOAD_USER
              value: ""
            - name: UPLOAD_PASSWORD
              value: ""
            - name: PUBLIC_OVERPASS_API_URL
              value: https://overpass-api.de
            - name: PUBLIC_VALHALLA_URL
              value: https://valhalla1.openstreetmap.de
            - name: PUBLIC_NOMINATIM_URL
              value: https://nominatim.openstreetmap.org
          volumeMounts:
            - name: uploads
              mountPath: /app/uploads
          resources:
            requests:
              cpu: 100m
              memory: 256Mi
            limits:
              cpu: 1000m
              memory: 1Gi
          livenessProbe:
            httpGet:
              path: /
              port: 3000
            initialDelaySeconds: 20
            periodSeconds: 15
            timeoutSeconds: 10
          readinessProbe:
            httpGet:
              path: /
              port: 3000
            initialDelaySeconds: 10
            periodSeconds: 5
            timeoutSeconds: 10
      volumes:
        - name: uploads
          persistentVolumeClaim:
            claimName: wanderer-data
