apiVersion: apps/v1
kind: Deployment
metadata:
  name: couchdb
  labels:
    app.kubernetes.io/name: couchdb
    app.kubernetes.io/part-of: obsidian-live-sync
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: couchdb
  template:
    metadata:
      labels:
        app: couchdb
        app.kubernetes.io/part-of: obsidian-live-sync
    spec:
      securityContext:
        runAsUser: 5984
        runAsGroup: 5984
        fsGroup: 5984
      affinity:
        nodeAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              preference:
                matchExpressions:
                  - key: region
                    operator: In
                    values:
                      - us
      containers:
        - name: couchdb
          image: couchdb:3.5.1
          ports:
            - containerPort: 5984
          env:
            - name: COUCHDB_USER
              value: "couchdb-admin"
            - name: COUCHDB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: couchdb-secret
                  key: COUCHDB_PASSWORD
          volumeMounts:
            - name: data
              mountPath: /opt/couchdb/data
            - name: config
              mountPath: /opt/couchdb/etc/local.d
            - name: local-ini
              mountPath: /opt/couchdb/etc/local.ini
              subPath: local.ini
          resources:
            requests:
              cpu: 50m
              memory: 128Mi
            limits:
              memory: 512Mi
          # livenessProbe:
          #   httpGet:
          #     path: /_up
          #     port: 5984
          #   initialDelaySeconds: 30
          #   periodSeconds: 60
          #   timeoutSeconds: 5
          # readinessProbe:
          #   httpGet:
          #     path: /_up
          #     port: 5984
          #   initialDelaySeconds: 10
          #   periodSeconds: 10
          #   timeoutSeconds: 5
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: couchdb-data
        - name: config
          persistentVolumeClaim:
            claimName: couchdb-config
        - name: local-ini
          configMap:
            name: couchdb-config
