- hostname: home.bosscher.ch
  service: http://homepage.homepage.svc.cluster.local:3000
- hostname: n8n.bosscher.ch
  service: http://n8n.n8n.svc.cluster.local:5678
- hostname: fusion.bosscher.ch
  service: http://fusion.fusion.svc.cluster.local:8080
- hostname: shiori.bosscher.ch
  service: http://shiori.shiori.svc.cluster.local:8080
- hostname: obsidian-live-sync.bosscher.ch
  service: http://couchdb.obsidian-live-sync.svc.cluster.local:5984
- hostname: your-spotify.bosscher.ch
  service: http://your-spotify-web.your-spotify.svc.cluster.local:3000
- hostname: your-spotify-api.bosscher.ch
  service: http://your-spotify-server.your-spotify.svc.cluster.local:8080
- hostname: wanderer.bosscher.ch
  service: http://wanderer.wanderer.svc.cluster.local:3000
- hostname: norish.bosscher.ch
  service: http://norish.norish.svc.cluster.local:3000
- hostname: perplexica.bosscher.ch
  service: http://perplexica.perplexica.svc.cluster.local:3000
- hostname: stacks.bosscher.ch
  service: http://stacks.books.svc.cluster.local:7788
- hostname: calibre-web.bosscher.ch
  service: http://calibre-web.books.svc.cluster.local:8083
- hostname: audiobookshelf.bosscher.ch
  service: http://audiobookshelf.audiobookshelf.svc.cluster.local:80
- hostname: bookshelf.bosscher.ch
  service: http://bookshelf.bookshelf.svc.cluster.local:8787
- hostname: listenarr.bosscher.ch
  service: http://listenarr.listenarr.svc.cluster.local:5000
- hostname: stremio.bosscher.ch
  service: http://stremio.stremio.svc.cluster.local:8080
- hostname: aiostreams.bosscher.ch
  service: http://aiostreams.aiostreams.svc.cluster.local:3000
- hostname: it-tools.bosscher.ch
  service: http://it-tools.it-tools.svc.cluster.local:8080
- hostname: docspell.bosscher.ch
  service: http://docspell-restserver.docspell.svc.cluster.local:7880
- hostname: sabnzbd.bosscher.ch
  service: http://sabnzbd.sabnzbd.svc.cluster.local:8085
- hostname: prowlarr.bosscher.ch
  service: http://prowlarr.prowlarr.svc.cluster.local:9696
- hostname: rdt-client.bosscher.ch
  service: http://rdt-client.rdt-client.svc.cluster.local:6500
- hostname: qbittorrent.bosscher.ch
  service: http://qbittorrent.qbittorrent.svc.cluster.local:8080
- hostname: radarr.bosscher.ch
  service: http://radarr.radarr.svc.cluster.local:7878
- hostname: sonarr.bosscher.ch
  service: http://sonarr.sonarr.svc.cluster.local:8989
- hostname: kite.bosscher.ch
  service: http://kite.kube-system.svc.cluster.local:8080
- hostname: argocd.bosscher.ch
  service: https://argocd-server.argocd.svc.cluster.local
  originRequest:
    noTLSVerify: true
- hostname: longhorn.bosscher.ch
  service: http://longhorn-frontend.longhorn-system.svc.cluster.local:80
- hostname: gatus.bosscher.ch
  service: http://gatus.gatus.svc.cluster.local:8080
- hostname: grafana.bosscher.ch
  service: http://prometheus-grafana.monitoring.svc.cluster.local:80
- hostname: bentopdf.bosscher.ch
  service: http://bentopdf.bentopdf.svc.cluster.local:8080
- hostname: surfsense.bosscher.ch
  service: http://surfsense-frontend.surfsense.svc.cluster.local:3000
- hostname: surfsense-backend.bosscher.ch
  service: http://surfsense-backend.surfsense.svc.cluster.local:8000
- hostname: linkwarden.bosscher.ch
  service: http://linkwarden.linkwarden.svc.cluster.local:3000
