apiVersion: apps/v1
kind: Deployment
metadata:
  name: your-spotify-server
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: your-spotify-server
  template:
    metadata:
      labels:
        app.kubernetes.io/name: your-spotify-server
        app.kubernetes.io/part-of: your-spotify
    spec:
      affinity:
        nodeAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              preference:
                matchExpressions:
                  - key: region
                    operator: In
                    values:
                      - us
        podAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              podAffinityTerm:
                labelSelector:
                  matchLabels:
                    app.kubernetes.io/part-of: your-spotify
                topologyKey: kubernetes.io/hostname
      containers:
        - name: server
          image: "yooooomi/your_spotify_server:1.15.0"
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          env:
            - name: API_ENDPOINT
              value: https://your-spotify-api.bosscher.ch
            - name: CLIENT_ENDPOINT
              value: https://your-spotify.bosscher.ch
            - name: MONGO_ENDPOINT
              value: mongodb://your-spotify-mongo:27017/your_spotify
            - name: CORS
              value: "http://your-spotify-web:3000,https://your-spotify.bosscher.ch,https://your-spotify-api.bosscher.ch"
            - name: SPOTIFY_PUBLIC
              valueFrom:
                secretKeyRef:
                  name: your-spotify-secrets
                  key: SPOTIFY_PUBLIC
            - name: SPOTIFY_SECRET
              valueFrom:
                secretKeyRef:
                  name: your-spotify-secrets
                  key: SPOTIFY_SECRET
          resources:
            requests:
              cpu: 50m
              memory: 128Mi
            limits:
              memory: 256Mi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: your-spotify-web
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: your-spotify-web
  template:
    metadata:
      labels:
        app.kubernetes.io/name: your-spotify-web
        app.kubernetes.io/part-of: your-spotify
    spec:
      affinity:
        nodeAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              preference:
                matchExpressions:
                  - key: region
                    operator: In
                    values:
                      - us
        podAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              podAffinityTerm:
                labelSelector:
                  matchLabels:
                    app.kubernetes.io/part-of: your-spotify
                topologyKey: kubernetes.io/hostname
      containers:
        - name: web
          image: "yooooomi/your_spotify_client:1.15.0"
          ports:
            - name: http
              containerPort: 3000
              protocol: TCP
          env:
            - name: NODE_ENV
              value: production
            - name: API_ENDPOINT
              value: https://your-spotify-api.bosscher.ch
            - name: MONGO_ENDPOINT
              value: mongodb://your-spotify-mongo:27017/your_spotify
          resources:
            requests:
              cpu: 25m
              memory: 64Mi
            limits:
              memory: 128Mi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: your-spotify-mongo
spec:
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app.kubernetes.io/name: your-spotify-mongo
  template:
    metadata:
      labels:
        app.kubernetes.io/name: your-spotify-mongo
        app.kubernetes.io/part-of: your-spotify
    spec:
      affinity:
        nodeAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              preference:
                matchExpressions:
                  - key: region
                    operator: In
                    values:
                      - us
        podAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              podAffinityTerm:
                labelSelector:
                  matchLabels:
                    app.kubernetes.io/part-of: your-spotify
                topologyKey: kubernetes.io/hostname
      containers:
        - name: mongo
          image: "mongo:8.2.2"
          ports:
            - name: mongo
              containerPort: 27017
              protocol: TCP
          volumeMounts:
            - name: data
              mountPath: /data/db
          resources:
            requests:
              cpu: 50m
              memory: 512Mi
            limits:
              memory: 1024Mi
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: your-spotify-mongo-data
