apiVersion: apps/v1
kind: Deployment
metadata:
  name: aiometadata
  labels:
    app.kubernetes.io/name: aiometadata
    app.kubernetes.io/part-of: homelab
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: aiometadata
  template:
    metadata:
      labels:
        app: aiometadata
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: region
                    operator: In
                    values:
                      - europe
        # podAffinity to ensure aiometadata and aiometadata-redis are on the same node
        podAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchLabels:
                  app: aiometadata-redis
              topologyKey: "kubernetes.io/hostname"
      containers:
        - name: aiometadata
          # Doesn't publish tags for versions
          image: ghcr.io/cedya77/aiometadata:latest
          ports:
            - containerPort: 3232
          env:
            - name: PORT
              value: "3232"
            - name: REDIS_URL
              value: "redis://aiometadata-redis:6379"
            - name: HOST_NAME
              value: "https://aiometadata.bosscher.ch"
            - name: LOG_LEVEL
              value: "info"
            - name: META_TTL
              value: "604800"
            - name: CATALOG_TTL
              value: "86400"
            - name: TMDB_TRENDING_TTL
              value: "10800"
            - name: CATALOG_LIST_ITEMS_SIZE
              value: "20"
            - name: DATABASE_URI
              value: "sqlite://addon/data/db.sqlite"
            - name: TMDB_API
              valueFrom:
                secretKeyRef:
                  name: aiometadata-secret
                  key: TMDB_API_KEY
            - name: TVDB_API_KEY
              valueFrom:
                secretKeyRef:
                  name: aiometadata-secret
                  key: TVDB_API_KEY
            - name: ADMIN_KEY
              valueFrom:
                secretKeyRef:
                  name: aiometadata-secret
                  key: ADMIN_KEY
          volumeMounts:
            - name: data
              mountPath: /app/addon/data
          resources:
            requests:
              cpu: 50m
              memory: 128Mi
            limits:
              memory: 512Mi
          livenessProbe:
            tcpSocket:
              port: 3232
            initialDelaySeconds: 10
            periodSeconds: 30
          readinessProbe:
            tcpSocket:
              port: 3232
            initialDelaySeconds: 5
            periodSeconds: 10
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: aiometadata-data
