apiVersion: v1
kind: ConfigMap
metadata:
  name: searxng-config
  labels:
    app: perplexica
data:
  settings.yml.template: |
    use_default_settings: true
    server:
      limiter: false
      image_proxy: true
    redis:
      url: redis://perplexica-redis:6379/0
