apiVersion: apps/v1
kind: Deployment
metadata:
  name: perplexica-searxng
  annotations:
    reloader.stakater.com/auto: "true"
  labels:
    app.kubernetes.io/name: perplexica-searxng
    app.kubernetes.io/part-of: homelab
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: perplexica-searxng
  template:
    metadata:
      labels:
        app: perplexica-searxng
        app-group: perplexica-stack
    spec:
      affinity:
        nodeAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              preference:
                matchExpressions:
                  - key: region
                    operator: In
                    values:
                      - europe
        podAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: app-group
                    operator: In
                    values:
                      - perplexica-stack
              topologyKey: kubernetes.io/hostname
      containers:
        - name: searxng
          image: docker.io/searxng/searxng:latest
          ports:
            - containerPort: 8080
          env:
            - name: SEARXNG_SECRET
              valueFrom:
                secretKeyRef:
                  name: searxng-secret
                  key: secret_key
            - name: SEARXNG_BASE_URL
              value: "perplexica-searxng.perplexica.svc.cluster.local:8080"
            - name: SEARCHXNG_OUTPUT
              value: ["json", "html"]
          volumeMounts:
            - name: searxng-config
              mountPath: /etc/searxng
            - name: searxng-data
              mountPath: /var/cache/searxng
          resources:
            requests:
              cpu: 50m
              memory: 128Mi
            limits:
              memory: 512Mi
      volumes:
        - name: searxng-config-template
          configMap:
            name: searxng-config
        - name: searxng-config
          emptyDir: {}
        - name: searxng-data
          persistentVolumeClaim:
            claimName: perplexica-searxng-data
